---

- import_tasks: sway.yml
  tags: sway
- import_tasks: bluetooth.yml
  tags: bluetooth
- import_tasks: cups.yml
  tags: cups
- import_tasks: flatpak.yml
  tags: flatpak
- import_tasks: chromium.yml
  tags: chromium
- import_tasks: dbeaver.yml
  tags: dbeaver
- import_tasks: discord.yml
  tags: discord
- import_tasks: driver.yml
  tags: driver
- import_tasks: fcitx5.yml
  tags: fcitx5
- import_tasks: firefox.yml
  tags: firefox
- import_tasks: fonts.yml
  tags: fonts
- import_tasks: joplin.yml
  tags: joplin
- import_tasks: multimedia.yml
  tags: multimedia
- import_tasks: network.yml
  tags: network
- import_tasks: postman.yml
  tags: postman
- import_tasks: remmina.yml
  tags: remmina
- import_tasks: signal.yml
  tags: signal
- import_tasks: slack.yml
  tags: slack
- import_tasks: skype.yml
  tags: skype
- import_tasks: zoom.yml
  tags: zoom
