---

- import_tasks: fzf.yml
- import_tasks: yarn.yml    # required by plugin installation (ex.: iamcco/markdown-preview.nvim)

- name: Install fd, neovim, ripgrep
  pacman:
    name:
      - fd
      - neovim
      - ripgrep
    state: present
  become: yes

- name: Config fish for neovim
  copy:
    src: fish/neovim.fish
    dest: "{{ ansible_user_dir }}/.config/fish/conf.d/"
  tags: fish

- name: Copy neovim config
  copy:
    src: neovim/
    dest: "{{ ansible_user_dir }}/.config/nvim/"

- name: Create $HOME/.local/share/nvim/site/autoload directory if it does not exist
  file:
    path: "{{ ansible_user_dir }}/.local/share/nvim/site/autoload"
    state: directory

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ ansible_user_dir }}/.local/share/nvim/site/autoload/"

- name: Install neovim plugins
  shell: nvim +PlugUpdate +qall

- name: Install pynvim
  pip:
    name: pynvim
    executable: "{{ ansible_user_dir }}/.local/bin/pip"
    extra_args: --user
    state: latest
